version: '3.8'

services:
  client:
    image: pwgrs.azurecr.io/client:latest
    ports:
      - '80:5173'
    depends_on:
      - server

  server:
    image: pwgrs.azurecr.io/server:latest
    ports:
      - '3001:3001'
    networks:
      - app-network
    depends_on:
      - mongo

  mongo:
    image: mongo:8.0.15
    ports:
      - '27017:27017'
    networks:
      - app-network
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASSWORD

volumes:
  mongo_data:

networks:
  app-network:
    driver: bridge
