FROM node:22-alpine3.21

WORKDIR /server

COPY package*.json .

ENV NODE_ENV=production

RUN echo "NODE_ENV before: $NODE_ENV"
RUN npm i

COPY . .
RUN npm run build

COPY . .
RUN cp -R public dist/public

EXPOSE 3001

CMD ["npm", "run", "start"]
